services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_USER=yourdbuser
      - DB_PASSWORD=yourdbpassword
      - DB_NAME=yourdbname
      - DB_PORT=5432
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
      POSTGRES_DB: yourdbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  postgres_data: