global:
  scrape_interval: 30s  # Scrape every 30 seconds (longer interval to reduce load)
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'chat-app'
    static_configs:
      - targets: ['app:6060']  # Scrape your Go application's expvar endpoint

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']  # Assuming you use postgres_exporter on the default port

  - job_name: 'rabbitmq_exporter'
    static_configs:
      - targets: ['rabbitmq_exporter:9419'] # Assuming use rabbitmq_exporter on the default port.

  - job_name: 'prometheus' # You can monitor promethues with itself.
    static_configs:
      - targets: ['localhost:9090']